### ISSUE TITLE
TypeError: Cannot read property 'token' of undefined

### ISSUE THREAD

**Issue by flo5324** [alexispe/georide-web-extension#1]
Impossible de charger la liste des évènements.
Lors du clic sur "Mes derniers évènements" on obtient l'erreur 
`TypeError: Cannot read property 'token' of undefined`

J'imagine que cela vient de la fonction `getTrackerEvents` dans `georide.api.js`

Extension: version 2.1.0
Navigateur: Brave version 1.11.104 Chromium: 84.0.4147.105 (Build officiel) (64 bits)

**Comment by alexispe** [comment]
Merci pour ton retour.

C'est corrigé, la version est en cours de validation par Google et Mozilla.
